### ISSUE TITLE
RuntimeError: Error parsing task config

### ISSUE THREAD

**Issue by arozehnal** [thehunmonkgroup/onenote#1]
I am running task v.2.5.1 on MSYS platform.

When I add this lines:
task config uda.notes.type string
task config uda.notes.label Notes

to .taskrc then task/vit will not start.

$ vit
Traceback (most recent call last):
  File "/usr/bin/vit", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/vit/command_line.py", line 5, in main
    Application(options, filters)
  File "/usr/lib/python3.8/site-packages/vit/application.py", line 70, in __init__
    self.load_early_config()
  File "/usr/lib/python3.8/site-packages/vit/application.py", line 78, in load_early_config
    self.task_config = TaskParser(self.config)
  File "/usr/lib/python3.8/site-packages/vit/config_parser.py", line 197, in __init__
    self.get_task_config()
  File "/usr/lib/python3.8/site-packages/vit/config_parser.py", line 212, in get_task_config
    raise RuntimeError('Error parsing task config: %s' % stderr)
RuntimeError: Error parsing task config: Malformed entry 'task config uda.notes.type string' in config file.

Any suggestion?

**Comment by thehunmonkgroup** [comment]
```dosini
uda.notes.type=string
uda.notes.label=Notes
```
